spring.application.name=SpringWIthoutAppContext

# Will set using @Value("${paymentGateway.type}")
payment-gateway.type = paytm
payment-gateway.retry-count = 5

# Properties should follow canonical naming convention
# Will set using @ConfigurationProperties("payment-property") on class
payment-property.type = paytm
payment-property.retry-count = 5
payment-property.enabled = true
payment-property.timeout = 3000
